import { db } from './db';
import {
  users,
  grades,
  subjects,
  games,
  gameSubjects,
  badges
} from '@shared/schema';

async function seedDatabase() {
  console.log('Starting database seeding...');

  // Add grades
  console.log('Seeding grades...');
  const gradesData = [
    { id: 1, name: "PreK", slug: "prek", displayOrder: 1, color: "#FF9F1C", icon: "star", description: "Games for Pre-Kindergarten students ages 3-5" },
    { id: 2, name: "Kindergarten", slug: "kindergarten", displayOrder: 2, color: "#FF4D6D", icon: "apple-alt", description: "Games for Kindergarten students ages 5-6" },
    { id: 3, name: "1st Grade", slug: "grade-1", displayOrder: 3, color: "#7209B7", icon: "pencil-alt", description: "Games for 1st Grade students ages 6-7" },
    { id: 4, name: "2nd Grade", slug: "grade-2", displayOrder: 4, color: "#4CC9F0", icon: "book", description: "Games for 2nd Grade students ages 7-8" },
    { id: 5, name: "3rd Grade", slug: "grade-3", displayOrder: 5, color: "#8AC926", icon: "calculator", description: "Games for 3rd Grade students ages 8-9" },
    { id: 6, name: "4th Grade", slug: "grade-4", displayOrder: 6, color: "#1982C4", icon: "globe-americas", description: "Games for 4th Grade students ages 9-10" },
  ];

  await db.insert(grades).values(gradesData).onConflictDoNothing();

  // Add subjects
  console.log('Seeding subjects...');
  const subjectsData = [
    { id: 1, name: "Math", slug: "math", icon: "calculator", color: "#4361ee", displayOrder: 1, description: "Games that teach math concepts and skills" },
    { id: 2, name: "Reading", slug: "reading", icon: "book", color: "#7209b7", displayOrder: 2, description: "Games that improve reading and literacy" },
    { id: 3, name: "Science", slug: "science", icon: "flask", color: "#38b000", displayOrder: 3, description: "Games that explore scientific concepts" },
    { id: 4, name: "Social Studies", slug: "social-studies", icon: "globe", color: "#fb8500", displayOrder: 4, description: "Games about history, geography, and culture" },
    { id: 5, name: "Art", slug: "art", icon: "palette", color: "#f72585", displayOrder: 5, description: "Games that inspire creativity and artistic expression" },
    { id: 6, name: "Music", slug: "music", icon: "music", color: "#3a0ca3", displayOrder: 6, description: "Games that teach music skills and appreciation" },
    { id: 7, name: "Typing", slug: "typing", icon: "keyboard", color: "#4895ef", displayOrder: 7, description: "Games that help develop typing skills" },
    { id: 8, name: "Logic", slug: "logic", icon: "brain", color: "#ff9f1c", displayOrder: 8, description: "Games that develop critical thinking and problem solving" },
  ];

  await db.insert(subjects).values(subjectsData).onConflictDoNothing();

  // Add games - including all 20 new 1st grade games
  console.log('Seeding games...');
  const gamesData = [
    // New 1st Grade Games (20 games)
    {
      id: 21,
      title: "Addition Arcade",
      slug: "addition-arcade",
      description: "Solve addition problems to earn stars in this colorful arcade game! Perfect for 1st graders learning basic math.",
      instructions: "Look at the math problem and type your answer. Click Check Answer to see if you're correct!",
      educationalBenefits: "Practice basic addition, develop number sense, build math confidence",
      thumbnail: "addition-arcade.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["addition", "math", "numbers"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.9,
      learningOutcomes: "Students will master basic addition facts 1-10",
      curriculumStandards: "Meets Common Core Math Standards 1.OA.A.1",
      accessibility: "Keyboard controls, high contrast mode"
    },
    {
      id: 22,
      title: "Subtraction Safari",
      slug: "subtraction-safari",
      description: "Help safari animals learn subtraction! Solve problems to discover amazing animals in their natural habitats.",
      instructions: "Count the animals and solve the subtraction problem. Find safari animals as you learn!",
      educationalBenefits: "Practice subtraction, learn about animals, develop counting skills",
      thumbnail: "subtraction-safari.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["subtraction", "math", "animals"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.8,
      learningOutcomes: "Students will master basic subtraction facts 1-10",
      curriculumStandards: "Meets Common Core Math Standards 1.OA.A.1",
      accessibility: "Keyboard controls, visual counting aids"
    },
    {
      id: 23,
      title: "Spelling Bee Garden",
      slug: "spelling-bee-garden",
      description: "Listen to words and spell them correctly to grow a beautiful flower garden! Audio-based spelling practice.",
      instructions: "Listen to the word, then type the spelling. Grow flowers for each correct answer!",
      educationalBenefits: "Improve spelling, enhance listening skills, build vocabulary",
      thumbnail: "spelling-bee-garden.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["spelling", "reading", "phonics"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 12,
      averageRating: 4.9,
      learningOutcomes: "Students will improve spelling of common 1st grade words",
      curriculumStandards: "Meets Common Core Language Standards 1.L.2",
      accessibility: "Audio pronunciation, keyboard controls"
    },
    {
      id: 24,
      title: "Sight Word Memory",
      slug: "sight-word-memory",
      description: "Match pairs of sight words in this memory game! Learn essential reading words through fun gameplay.",
      instructions: "Click cards to flip them and find matching sight word pairs. Remember where each word is!",
      educationalBenefits: "Learn sight words, improve memory, enhance reading fluency",
      thumbnail: "sight-word-memory.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["sight-words", "reading", "memory"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 10,
      averageRating: 4.8,
      learningOutcomes: "Students will recognize common sight words instantly",
      curriculumStandards: "Meets Common Core Reading Standards 1.RF.3.g",
      accessibility: "Keyboard navigation, high contrast mode"
    },
    {
      id: 25,
      title: "Rhyming Rockets",
      slug: "rhyming-rockets",
      description: "Launch rockets by finding rhyming words! Space-themed phonics adventure for young learners.",
      instructions: "Find words that rhyme with the target word to launch rockets into space!",
      educationalBenefits: "Develop phonics skills, learn rhyming patterns, improve word recognition",
      thumbnail: "rhyming-rockets.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["rhyming", "phonics", "reading"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 12,
      averageRating: 4.9,
      learningOutcomes: "Students will identify rhyming words and understand sound patterns",
      curriculumStandards: "Meets Common Core Reading Standards 1.RF.2.a",
      accessibility: "Audio support, space-themed visuals"
    },
    {
      id: 26,
      title: "Telling Time Puzzle",
      slug: "telling-time-puzzle",
      description: "Learn to read analog clocks with colorful time puzzles! Practice telling time to the hour and half hour.",
      instructions: "Look at the clock and choose the correct time. Learn about hour and minute hands!",
      educationalBenefits: "Learn time concepts, practice reading clocks, understand daily schedules",
      thumbnail: "telling-time-puzzle.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["time", "math", "clocks"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.7,
      learningOutcomes: "Students will read analog clocks to the hour and half hour",
      curriculumStandards: "Meets Common Core Math Standards 1.MD.B.3",
      accessibility: "Large clock faces, clear time indicators"
    },
    {
      id: 27,
      title: "Animal Habitat Match",
      slug: "animal-habitat-match",
      description: "Help animals find their homes! Learn about different habitats where animals live around the world.",
      instructions: "Match each animal to its correct habitat. Learn where different animals live!",
      educationalBenefits: "Learn about animal habitats, develop classification skills, understand ecosystems",
      thumbnail: "animal-habitat-match.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["science", "animals", "habitats"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 12,
      averageRating: 4.8,
      learningOutcomes: "Students will identify animal habitats and understand ecosystems",
      curriculumStandards: "Meets Next Generation Science Standards K-LS1-1",
      accessibility: "Visual habitat representations, animal sounds"
    },
    {
      id: 28,
      title: "Life Cycle Sort",
      slug: "life-cycle-sort",
      description: "Put life cycle stages in correct order! Learn how butterflies, frogs, and chickens grow and change.",
      instructions: "Drag the life cycle stages into the correct order from first to last!",
      educationalBenefits: "Understand life cycles, learn sequence and order, develop scientific thinking",
      thumbnail: "life-cycle-sort.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["science", "life-cycles", "biology"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 8,
      maxPlayTime: 15,
      averageRating: 4.7,
      learningOutcomes: "Students will understand basic life cycles of common animals",
      curriculumStandards: "Meets Next Generation Science Standards 1-LS1-2",
      accessibility: "Drag and drop alternative, clear stage progression"
    },
    {
      id: 29,
      title: "Shapes & Geometry",
      slug: "shapes-geometry",
      description: "Identify shapes and learn geometry basics! Practice recognizing circles, triangles, squares, and rectangles.",
      instructions: "Look at each shape and choose its correct name. Learn about different geometric shapes!",
      educationalBenefits: "Recognize geometric shapes, develop spatial awareness, learn shape properties",
      thumbnail: "shapes-geometry.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["math", "geometry", "shapes"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 12,
      averageRating: 4.8,
      learningOutcomes: "Students will identify and name basic geometric shapes",
      curriculumStandards: "Meets Common Core Math Standards 1.G.A.1",
      accessibility: "High contrast shapes, shape tracing options"
    },
    {
      id: 30,
      title: "Vowel Sorting",
      slug: "vowel-sorting",
      description: "Learn short and long vowel sounds! Listen to words and identify if they have short or long vowels.",
      instructions: "Listen to each word and decide if it has a short or long vowel sound!",
      educationalBenefits: "Distinguish vowel sounds, improve phonics skills, enhance reading ability",
      thumbnail: "vowel-sorting.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["phonics", "vowels", "reading"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 12,
      averageRating: 4.9,
      learningOutcomes: "Students will distinguish between short and long vowel sounds",
      curriculumStandards: "Meets Common Core Reading Standards 1.RF.2.a",
      accessibility: "Clear audio pronunciation, visual vowel guides"
    },
    {
      id: 31,
      title: "Patterns & Sequences",
      slug: "patterns-sequences",
      description: "Find what comes next in colorful patterns! Develop logical thinking with shapes, colors, and objects.",
      instructions: "Look at the pattern and choose what comes next. Find the repeating sequence!",
      educationalBenefits: "Develop pattern recognition, logical thinking, mathematical reasoning",
      thumbnail: "patterns-sequences.jpg",
      gameType: "react",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["logic", "patterns", "math"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.8,
      learningOutcomes: "Students will recognize and continue simple patterns",
      curriculumStandards: "Meets Common Core Math Standards 1.OA.D.8",
      accessibility: "Clear pattern visualization, step-by-step hints"
    },

    // New AI-Themed 3rd Grade Games (10 interactive games with advanced features)
    {
      id: 200,
      title: "AI Robot Builder",
      slug: "ai-robot-builder",
      description: "Design and program your own AI robot! Learn basic coding concepts while building amazing robots with different abilities.",
      instructions: "Drag code blocks to program your robot, test its movements, and complete challenges!",
      educationalBenefits: "Learn basic programming logic, understand AI concepts, develop problem-solving skills, practice sequential thinking",
      thumbnail: "ai-robot-builder.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "programming", "robotics", "logic"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 25,
      averageRating: 4.9,
      learningOutcomes: "Students will understand basic programming concepts and AI logic",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-AP-10, 1A-AP-14",
      accessibility: "Visual programming blocks, audio instructions, step-by-step hints"
    },
    {
      id: 201,
      title: "Machine Learning Detective",
      slug: "machine-learning-detective",
      description: "Solve mysteries using AI pattern recognition! Train your detective AI to identify clues and solve cases.",
      instructions: "Look for patterns in the evidence, train your AI helper, and crack the case!",
      educationalBenefits: "Understand pattern recognition, learn data analysis, develop critical thinking, practice observation skills",
      thumbnail: "machine-learning-detective.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "patterns", "detective", "analysis"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 12,
      maxPlayTime: 20,
      averageRating: 4.8,
      learningOutcomes: "Students will recognize patterns and understand basic machine learning concepts",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-DA-05, 1A-DA-06",
      accessibility: "Visual clue highlighting, audio descriptions, interactive hints"
    },
    {
      id: 202,
      title: "Smart City Planner",
      slug: "smart-city-planner",
      description: "Design a futuristic smart city with AI technology! Place buildings, manage traffic, and make the city efficient.",
      instructions: "Drag buildings onto the map, connect them with smart roads, and watch your AI city come to life!",
      educationalBenefits: "Learn about urban planning, understand AI applications, practice spatial reasoning, develop systems thinking",
      thumbnail: "smart-city-planner.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "city-planning", "engineering", "systems"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 15,
      maxPlayTime: 30,
      averageRating: 4.7,
      learningOutcomes: "Students will understand smart systems and basic engineering principles",
      curriculumStandards: "Meets NGSS 3-5-ETS1-1, 3-5-ETS1-2",
      accessibility: "Drag-and-drop alternatives, city overview maps, building descriptions"
    },
    {
      id: 203,
      title: "Neural Network Adventure",
      slug: "neural-network-adventure",
      description: "Journey through a brain-like network! Help signals travel through neurons to solve puzzles and learn how AI thinks.",
      instructions: "Connect the neurons by drawing paths, activate signals, and watch how information flows!",
      educationalBenefits: "Understand neural networks, learn about brain function, practice logical connections, develop scientific thinking",
      thumbnail: "neural-network-adventure.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "hard",
      tags: ["ai", "neural-networks", "brain", "connections"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 20,
      averageRating: 4.6,
      learningOutcomes: "Students will understand basic neural network concepts and brain function",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-AP-15",
      accessibility: "Simplified neuron visuals, connection highlighting, step-by-step tutorials"
    },
    {
      id: 204,
      title: "AI Voice Assistant Lab",
      slug: "ai-voice-assistant-lab",
      description: "Create your own voice assistant! Teach it to understand commands and help people with daily tasks.",
      instructions: "Record voice commands, train your assistant, and test how well it responds to different requests!",
      educationalBenefits: "Learn about voice recognition, understand natural language processing, practice communication skills",
      thumbnail: "ai-voice-assistant-lab.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "voice", "assistant", "language"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 8,
      maxPlayTime: 18,
      averageRating: 4.8,
      learningOutcomes: "Students will understand voice recognition and natural language processing",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-IC-16",
      accessibility: "Text alternatives for voice commands, visual feedback, keyboard input options"
    },
    {
      id: 205,
      title: "Autonomous Car Racing",
      slug: "autonomous-car-racing",
      description: "Program self-driving cars to race around tracks! Learn how AI helps cars navigate safely and efficiently.",
      instructions: "Set up sensors, program driving rules, and watch your autonomous car race to victory!",
      educationalBenefits: "Understand autonomous systems, learn about sensors, practice algorithm design, develop engineering skills",
      thumbnail: "autonomous-car-racing.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "autonomous", "cars", "sensors"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 12,
      maxPlayTime: 25,
      averageRating: 4.9,
      learningOutcomes: "Students will understand autonomous systems and sensor technology",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-AP-11",
      accessibility: "Track overview, sensor visualization, simplified controls"
    },
    {
      id: 206,
      title: "AI Art Generator",
      slug: "ai-art-generator",
      description: "Create amazing artwork with AI! Learn how computers can be creative and generate beautiful art from simple inputs.",
      instructions: "Choose colors and shapes, give the AI prompts, and watch it create unique artwork!",
      educationalBenefits: "Explore AI creativity, understand generative art, develop artistic skills, learn about algorithms",
      thumbnail: "ai-art-generator.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["ai", "art", "creativity", "generation"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 8,
      maxPlayTime: 20,
      averageRating: 4.7,
      learningOutcomes: "Students will understand AI creativity and generative algorithms",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-AP-13",
      accessibility: "Color picker alternatives, art description audio, simple creation tools"
    },
    {
      id: 207,
      title: "Chatbot Conversation Club",
      slug: "chatbot-conversation-club",
      description: "Build friendly chatbots that can have conversations! Teach them responses and watch them learn to chat better.",
      instructions: "Type conversation examples, train your chatbot, and have fun conversations with AI friends!",
      educationalBenefits: "Learn conversational AI, practice language skills, understand chatbot logic, develop communication abilities",
      thumbnail: "chatbot-conversation-club.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "chatbot", "conversation", "language"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 22,
      averageRating: 4.8,
      learningOutcomes: "Students will understand conversational AI and natural language interaction",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-IC-17",
      accessibility: "Chat history, conversation templates, typing assistance"
    },
    {
      id: 208,
      title: "Predictive Weather AI",
      slug: "predictive-weather-ai",
      description: "Train an AI to predict the weather! Analyze patterns in weather data and help the AI make accurate forecasts.",
      instructions: "Look at weather patterns, feed data to your AI, and see how well it predicts tomorrow's weather!",
      educationalBenefits: "Understand prediction algorithms, learn data analysis, practice pattern recognition, explore meteorology",
      thumbnail: "predictive-weather-ai.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["ai", "weather", "prediction", "data"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 18,
      averageRating: 4.6,
      learningOutcomes: "Students will understand predictive algorithms and data patterns",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-DA-07",
      accessibility: "Weather symbol descriptions, data visualization, simplified charts"
    },
    {
      id: 209,
      title: "AI Game Master",
      slug: "ai-game-master",
      description: "Create an AI that can play games with you! Teach it rules, strategies, and watch it become a worthy opponent.",
      instructions: "Choose a game, teach the AI the rules, and challenge it to matches as it learns and improves!",
      educationalBenefits: "Understand game AI, learn strategy development, practice rule-based thinking, explore competitive algorithms",
      thumbnail: "ai-game-master.jpg",
      gameType: "react",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "hard",
      tags: ["ai", "games", "strategy", "competition"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 15,
      maxPlayTime: 30,
      averageRating: 4.8,
      learningOutcomes: "Students will understand game AI and strategic thinking algorithms",
      curriculumStandards: "Meets CSTA K-12 CS Standards 1A-AP-12",
      accessibility: "Game rule explanations, move highlighting, strategy hints"
    },

    // New 2nd Grade Games (10 exciting games with 3D thumbnails)
    {
      id: 100,
      title: "Space Math Explorer",
      slug: "space-math-explorer",
      description: "Blast off into space and solve 2-digit addition and subtraction problems! Help the astronaut collect stars and fuel for the rocket ship.",
      instructions: "Solve math problems to power your rocket and explore different planets. Use the number pad or click on answers!",
      educationalBenefits: "Master 2-digit addition and subtraction, develop mental math skills, practice regrouping",
      thumbnail: "space-math-explorer.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["addition", "subtraction", "2-digit", "space"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 8,
      maxPlayTime: 15,
      averageRating: 4.9,
      learningOutcomes: "Students will solve 2-digit addition and subtraction with regrouping",
      curriculumStandards: "Meets Common Core Math Standards 2.NBT.B.5-7",
      accessibility: "Large space-themed buttons, clear number display, audio feedback"
    },
    {
      id: 101,
      title: "Pirate Treasure Multiplication",
      slug: "pirate-treasure-multiplication",
      description: "Ahoy matey! Help Captain Multiply find buried treasure by solving multiplication tables from 1-5. Dig up coins and gems!",
      instructions: "Click on treasure chests with the correct multiplication answers. Avoid the wrong answers or you'll wake the sea monsters!",
      educationalBenefits: "Learn multiplication tables 1-5, develop quick recall, understand multiplication concepts",
      thumbnail: "pirate-treasure-multiplication.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["multiplication", "times-tables", "pirates", "treasure"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 18,
      averageRating: 4.8,
      learningOutcomes: "Students will master multiplication facts 1-5",
      curriculumStandards: "Meets Common Core Math Standards 2.OA.A.1",
      accessibility: "Pirate voice narration, colorful treasure visuals, large click targets"
    },
    {
      id: 102,
      title: "Grammar Castle Adventure",
      slug: "grammar-castle-adventure",
      description: "Enter the magical Grammar Castle and help the wizard sort nouns, verbs, and adjectives! Each correct answer unlocks a new room.",
      instructions: "Drag words into the correct grammar category bins. Complete each room to advance through the castle!",
      educationalBenefits: "Identify parts of speech, understand grammar fundamentals, build vocabulary",
      thumbnail: "grammar-castle-adventure.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["grammar", "nouns", "verbs", "adjectives", "castle"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 12,
      maxPlayTime: 20,
      averageRating: 4.7,
      learningOutcomes: "Students will identify and categorize basic parts of speech",
      curriculumStandards: "Meets Common Core Language Standards 2.L.1.a",
      accessibility: "Wizard voice guidance, magical sound effects, clear category labels"
    },
    {
      id: 103,
      title: "Dinosaur Fossil Fractions",
      slug: "dinosaur-fossil-fractions",
      description: "Become a paleontologist and dig up dinosaur fossils! Learn about halves, thirds, and fourths while uncovering T-Rex bones.",
      instructions: "Look at the fossil pieces and identify what fraction of the dinosaur skeleton you've found. Match fractions to complete dinosaurs!",
      educationalBenefits: "Understand basic fractions, recognize equal parts, develop visual fraction skills",
      thumbnail: "dinosaur-fossil-fractions.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["fractions", "dinosaurs", "fossils", "halves", "thirds"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 8,
      maxPlayTime: 15,
      averageRating: 4.9,
      learningOutcomes: "Students will identify and represent halves, thirds, and fourths",
      curriculumStandards: "Meets Common Core Math Standards 2.G.A.3",
      accessibility: "Dinosaur roar sound effects, clear fraction visualizations, dig animation"
    },
    {
      id: 104,
      title: "Superhero Sight Words",
      slug: "superhero-sight-words",
      description: "Join the Sight Word Squad and save the city! Read sight words quickly to power up your superhero abilities and defeat villains.",
      instructions: "Read the sight word on screen and click the matching word from the options. Speed and accuracy give you more superhero power!",
      educationalBenefits: "Master 2nd grade sight words, improve reading fluency, develop automatic word recognition",
      thumbnail: "superhero-sight-words.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["sight-words", "reading", "fluency", "superhero"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 16,
      averageRating: 4.8,
      learningOutcomes: "Students will recognize 2nd grade sight words automatically",
      curriculumStandards: "Meets Common Core Reading Standards 2.RF.3.f",
      accessibility: "Superhero sound effects, high contrast text, word pronunciation"
    },
    {
      id: 105,
      title: "Pizza Place Money Math",
      slug: "pizza-place-money-math",
      description: "Run your own pizza restaurant! Count coins and dollars to make correct change for hungry customers. Learn money values while having fun!",
      instructions: "Look at what customers order, add up the total cost, and give the correct change using coins and bills!",
      educationalBenefits: "Learn coin and bill values, practice addition with money, understand making change",
      thumbnail: "pizza-place-money-math.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["money", "coins", "addition", "restaurant", "pizza"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 12,
      maxPlayTime: 20,
      averageRating: 4.7,
      learningOutcomes: "Students will identify coin values and solve money problems",
      curriculumStandards: "Meets Common Core Math Standards 2.MD.C.8",
      accessibility: "Cash register sounds, clear money visuals, customer voice orders"
    },
    {
      id: 106,
      title: "Jungle Time Adventure",
      slug: "jungle-time-adventure",
      description: "Swing through the jungle with Timmy the Monkey! Learn to tell time to the hour and half-hour while exploring the rainforest.",
      instructions: "Help Timmy reach different jungle locations at the right time. Read the clocks and choose the correct time!",
      educationalBenefits: "Tell time to hour and half-hour, understand clock faces, develop time awareness",
      thumbnail: "jungle-time-adventure.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["time", "clocks", "jungle", "monkey", "hour"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 8,
      maxPlayTime: 14,
      averageRating: 4.8,
      learningOutcomes: "Students will tell time to the hour and half-hour",
      curriculumStandards: "Meets Common Core Math Standards 2.MD.C.7",
      accessibility: "Jungle animal sounds, large clock displays, monkey voice guide"
    },
    {
      id: 107,
      title: "Robot Reading Comprehension",
      slug: "robot-reading-comprehension",
      description: "Program your robot buddy by reading short stories and answering questions! Help the robot understand what it reads to complete missions.",
      instructions: "Read the story carefully, then answer questions about characters, setting, and what happened. Correct answers power up your robot!",
      educationalBenefits: "Improve reading comprehension, identify main ideas, understand story elements",
      thumbnail: "robot-reading-comprehension.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["reading", "comprehension", "stories", "robot", "questions"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 15,
      maxPlayTime: 25,
      averageRating: 4.9,
      learningOutcomes: "Students will demonstrate reading comprehension of grade-level texts",
      curriculumStandards: "Meets Common Core Reading Standards 2.RL.1-3",
      accessibility: "Robot voice narration, story illustrations, clear question text"
    },
    {
      id: 108,
      title: "Butterfly Garden Shapes",
      slug: "butterfly-garden-shapes",
      description: "Create a beautiful butterfly garden by identifying 2D and 3D shapes! Match shapes to grow flowers and attract colorful butterflies.",
      instructions: "Look at the shape shown and click on all matching shapes in the garden. Watch butterflies appear as you complete each level!",
      educationalBenefits: "Identify 2D and 3D shapes, understand shape properties, develop spatial reasoning",
      thumbnail: "butterfly-garden-shapes.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["shapes", "geometry", "2D", "3D", "butterflies", "garden"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 16,
      averageRating: 4.8,
      learningOutcomes: "Students will identify and describe 2D and 3D shapes",
      curriculumStandards: "Meets Common Core Math Standards 2.G.A.1",
      accessibility: "Butterfly flutter sounds, nature background music, shape name pronunciation"
    },
    {
      id: 109,
      title: "Magical Measuring Wizard",
      slug: "magical-measuring-wizard",
      description: "Become a measuring wizard and help magical creatures! Use rulers, measuring cups, and scales to solve measurement problems and brew potions.",
      instructions: "Use the measuring tools to find the length, weight, or volume needed for each magic spell. Choose the correct measurement unit!",
      educationalBenefits: "Learn measurement units, use measuring tools, understand length, weight, and volume",
      thumbnail: "magical-measuring-wizard.jpg",
      gameType: "react",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["measurement", "rulers", "units", "wizard", "magic", "tools"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 12,
      maxPlayTime: 18,
      averageRating: 4.7,
      learningOutcomes: "Students will measure length, weight, and volume using standard units",
      curriculumStandards: "Meets Common Core Math Standards 2.MD.A.1-4",
      accessibility: "Magical spell sounds, clear measuring tool visuals, wizard voice guidance"
    },

    {
      id: 1,
      title: "Math Adventure",
      slug: "math-adventure",
      description: "Join Captain Matheo on an exciting adventure through Number Island! Solve addition, subtraction, multiplication and division puzzles to unlock treasures and defeat the Math Monster.",
      instructions: "Use your mouse or touchscreen to select answers. Arrow keys can be used for movement on desktop.",
      educationalBenefits: "Practice basic arithmetic operations, develop mental math skills, learn problem-solving strategies, build math confidence through gameplay.",
      thumbnail: "math-adventure.jpg",
      gameType: "phaser",
      gradeId: 5, // 3rd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["addition", "subtraction", "multiplication", "division"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.7,
      learningOutcomes: "Students will practice basic arithmetic and develop quick mental calculation skills",
      curriculumStandards: "Meets Common Core Math Standards 3.OA.A.1, 3.OA.B.5",
      accessibility: "Keyboard controls, text-to-speech, high contrast mode"
    },
    {
      id: 2,
      title: "Word Wizards",
      slug: "word-wizards",
      description: "Become a Word Wizard by mastering spelling and vocabulary! Cast letter spells to create words and defeat the spelling monsters.",
      instructions: "Click on letters to spell words. Submit your answers by pressing the magic wand button.",
      educationalBenefits: "Improve spelling skills, expand vocabulary, practice word recognition, enhance reading comprehension.",
      thumbnail: "word-wizards.jpg",
      gameType: "phaser",
      gradeId: 3, // 1st Grade
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["spelling", "vocabulary", "reading"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 10,
      averageRating: 4.8,
      learningOutcomes: "Students will improve spelling skills and build vocabulary",
      curriculumStandards: "Meets Common Core Language Standards 1.L.2, 1.L.4",
      accessibility: "Keyboard controls, text-to-speech, high contrast mode"
    },
    {
      id: 3,
      title: "Science Lab",
      slug: "science-lab",
      description: "Conduct virtual experiments in your own Science Lab! Mix chemicals, observe reactions, and learn scientific concepts through hands-on activities.",
      instructions: "Drag and drop elements to combine them. Use tools from your toolkit to measure and analyze results.",
      educationalBenefits: "Learn scientific method, understand basic chemistry concepts, develop critical thinking skills, practice observation and analysis.",
      thumbnail: "science-lab.jpg",
      gameType: "phaser",
      gradeId: 6, // 4th Grade
      isPremium: false,
      isActive: true,
      difficulty: "hard",
      tags: ["experiments", "chemistry", "scientific-method"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 20,
      averageRating: 4.6,
      learningOutcomes: "Students will understand the scientific method and basic chemistry principles",
      curriculumStandards: "Meets Next Generation Science Standards 4-PS3-2, 4-PS3-4",
      accessibility: "Keyboard controls, text-to-speech, high contrast mode"
    },
    {
      id: 4,
      title: "Typing Adventure",
      slug: "typing-adventure",
      description: "Race through the forest by typing words correctly! Improve your typing speed and accuracy while having fun.",
      instructions: "Type the words that appear on the screen as quickly and accurately as possible to move your character forward.",
      educationalBenefits: "Develop typing skills, improve keyboard familiarity, enhance finger placement, increase typing speed and accuracy.",
      thumbnail: "typing-adventure.jpg",
      gameType: "createjs",
      gradeId: 4, // 2nd Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["typing", "keyboard-skills", "speed"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.5,
      learningOutcomes: "Students will improve typing speed and accuracy",
      curriculumStandards: "Meets ISTE Standards for Students 1.1.c, 1.1.d",
      accessibility: "High contrast mode, adjustable speed settings"
    },
    {
      id: 5,
      title: "Geography Explorer",
      slug: "geography-explorer",
      description: "Travel the world as a Geography Explorer! Visit different countries, learn about landmarks, and discover diverse cultures.",
      instructions: "Click on the map to answer geography questions. Collect stamps in your passport for correct answers.",
      educationalBenefits: "Learn world geography, understand cultural diversity, improve map reading skills, memorize countries and capitals.",
      thumbnail: "geography-explorer.jpg",
      gameType: "phaser",
      gradeId: 6, // 4th Grade
      isPremium: false,
      isActive: true,
      difficulty: "medium",
      tags: ["geography", "countries", "maps", "cultures"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 10,
      maxPlayTime: 20,
      averageRating: 4.9,
      learningOutcomes: "Students will learn geography and cultural diversity",
      curriculumStandards: "Meets Social Studies Standards SS.4.G.1, SS.4.G.2",
      accessibility: "Keyboard controls, text-to-speech, high contrast mode"
    },
    {
      id: 6,
      title: "ABC Animals",
      slug: "abc-animals",
      description: "Learn the alphabet with cute animal friends! Match letters to animals and hear the sounds they make.",
      instructions: "Click on the letter that matches the animal shown. Listen to the sound and repeat the letter name.",
      educationalBenefits: "Learn alphabet recognition, associate letters with animals, develop phonemic awareness, practice letter sounds.",
      thumbnail: "abc-animals.jpg",
      gameType: "createjs",
      gradeId: 1, // PreK
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["alphabet", "animals", "phonics"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 10,
      averageRating: 4.8,
      learningOutcomes: "Students will learn alphabet recognition and phonemic awareness",
      curriculumStandards: "Meets Foundational Skills Standards RF.K.1, RF.K.3",
      accessibility: "Audio instructions, large buttons, high contrast mode"
    },
    {
      id: 7,
      title: "Counting Fun",
      slug: "counting-fun",
      description: "Count objects, match numbers, and solve simple addition problems in this colorful counting game.",
      instructions: "Count the objects and click on the correct number. Drag objects to solve addition problems.",
      educationalBenefits: "Practice counting skills, recognize numbers, understand quantities, introduce basic addition concepts.",
      thumbnail: "counting-fun.jpg",
      gameType: "phaser",
      gradeId: 1, // PreK
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["counting", "numbers", "addition"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 10,
      averageRating: 4.7,
      learningOutcomes: "Students will practice counting and number recognition",
      curriculumStandards: "Meets Common Core Math Standards K.CC.A.1, K.CC.B.4",
      accessibility: "Audio instructions, large buttons, high contrast mode"
    },
    {
      id: 8,
      title: "Shape Match",
      slug: "shape-match",
      description: "Learn about shapes by matching them to everyday objects. Discover polygons, circles, and more!",
      instructions: "Drag shapes to match with the corresponding objects. Complete the puzzle to unlock new levels.",
      educationalBenefits: "Recognize geometric shapes, understand shape properties, improve spatial reasoning, connect shapes to real-world objects.",
      thumbnail: "shape-match.jpg",
      gameType: "createjs",
      gradeId: 1, // PreK
      isPremium: true,
      isActive: true,
      difficulty: "easy",
      tags: ["shapes", "geometry", "matching"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 10,
      averageRating: 4.6,
      learningOutcomes: "Students will recognize shapes and understand their properties",
      curriculumStandards: "Meets Common Core Math Standards K.G.A.1, K.G.B.4",
      accessibility: "Audio instructions, large buttons, high contrast mode"
    },
    {
      id: 9,
      title: "Color World",
      slug: "color-world",
      description: "Explore a vibrant world of colors! Mix primary colors, create art, and learn color recognition.",
      instructions: "Click on colors to select them. Mix colors by clicking the mixing pot. Paint objects with your chosen colors.",
      educationalBenefits: "Learn color recognition, understand color mixing, express creativity through art, develop fine motor skills.",
      thumbnail: "color-world.jpg",
      gameType: "phaser",
      gradeId: 1, // PreK
      isPremium: false,
      isActive: true,
      difficulty: "easy",
      tags: ["colors", "painting", "creativity"],
      createdAt: new Date(),
      updatedAt: new Date(),
      hasTextToSpeech: true,
      hasHighContrastMode: true,
      hasKeyboardControls: true,
      minPlayTime: 5,
      maxPlayTime: 15,
      averageRating: 4.9,
      learningOutcomes: "Students will learn color recognition and mixing",
      curriculumStandards: "Meets Visual Arts Standards VA:Cr1.1.Ka, VA:Cr2.1.Ka",
      accessibility: "Audio instructions, large buttons, high contrast mode"
    }
  ];

  await db.insert(games).values(gamesData).onConflictDoNothing();

  // Add game subjects
  console.log('Seeding game subjects...');
  const gameSubjectsData = [
    { id: 1, gameId: 1, subjectId: 1 }, // Math Adventure - Math
    { id: 2, gameId: 2, subjectId: 2 }, // Word Wizards - Reading
    { id: 3, gameId: 3, subjectId: 3 }, // Science Lab - Science
    { id: 4, gameId: 4, subjectId: 7 }, // Typing Adventure - Typing
    { id: 5, gameId: 5, subjectId: 4 }, // Geography Explorer - Social Studies
    { id: 6, gameId: 6, subjectId: 2 }, // ABC Animals - Reading
    { id: 7, gameId: 7, subjectId: 1 }, // Counting Fun - Math
    { id: 8, gameId: 8, subjectId: 1 }, // Shape Match - Math
    { id: 9, gameId: 9, subjectId: 5 }, // Color World - Art
  ];

  await db.insert(gameSubjects).values(gameSubjectsData).onConflictDoNothing();

  // Add badges
  console.log('Seeding badges...');
  const badgesData = [
    { id: 1, name: "Quick Solver", description: "Complete a game in record time", icon: "bolt", requirements: { timeUnder: 60 } },
    { id: 2, name: "Perfect Score", description: "Get 100% on any game", icon: "star", requirements: { score: 100 } },
    { id: 3, name: "Math Master", description: "Complete all math games", icon: "trophy", requirements: { completeAllInSubject: 1 } },
    { id: 4, name: "Problem Solver", description: "Solve 50 problems across all games", icon: "puzzle-piece", requirements: { totalProblems: 50 } },
  ];

  await db.insert(badges).values(badgesData).onConflictDoNothing();

  console.log('Database seeding completed!');
}

seedDatabase()
  .catch(e => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });